create table users (account_non_expired bit not null, account_non_locked bit not null, credentials_non_expired bit not null, enabled bit not null, role tinyint not null check ((role between 0 and 1)), created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6), username varchar(50) not null, email varchar(100) not null, password varchar(100) not null, primary key (id)) engine=InnoDB;
create index idx_username on users (username);
create index idx_email on users (email);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
create table users (account_non_expired bit not null, account_non_locked bit not null, credentials_non_expired bit not null, enabled bit not null, role tinyint not null check ((role between 0 and 1)), created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6), username varchar(50) not null, email varchar(100) not null, password varchar(100) not null, primary key (id)) engine=InnoDB;
create index idx_username on users (username);
create index idx_email on users (email);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
create table users (account_non_expired bit not null, account_non_locked bit not null, credentials_non_expired bit not null, enabled bit not null, role tinyint not null check ((role between 0 and 1)), created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6), username varchar(50) not null, email varchar(100) not null, password varchar(100) not null, primary key (id)) engine=InnoDB;
create index idx_username on users (username);
create index idx_email on users (email);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
create table users (account_non_expired bit not null, account_non_locked bit not null, credentials_non_expired bit not null, enabled bit not null, role tinyint not null check ((role between 0 and 1)), created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6), username varchar(50) not null, email varchar(100) not null, password varchar(100) not null, primary key (id)) engine=InnoDB;
create index idx_username on users (username);
create index idx_email on users (email);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
create table users (account_non_expired bit not null, account_non_locked bit not null, credentials_non_expired bit not null, enabled bit not null, role tinyint not null check ((role between 0 and 1)), created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6), username varchar(50) not null, email varchar(100) not null, password varchar(100) not null, primary key (id)) engine=InnoDB;
create index idx_username on users (username);
create index idx_email on users (email);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
create table users (account_non_expired bit not null, account_non_locked bit not null, credentials_non_expired bit not null, enabled bit not null, role tinyint not null check ((role between 0 and 1)), created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6), username varchar(50) not null, email varchar(100) not null, password varchar(100) not null, primary key (id)) engine=InnoDB;
create index idx_username on users (username);
create index idx_email on users (email);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
create table users (account_non_expired bit not null, account_non_locked bit not null, credentials_non_expired bit not null, enabled bit not null, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6), username varchar(50) not null, email varchar(100) not null, password varchar(100) not null, role enum ('ADMIN','USER') not null, primary key (id)) engine=InnoDB;
create index idx_username on users (username);
create index idx_email on users (email);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
create table users (account_non_expired bit not null, account_non_locked bit not null, credentials_non_expired bit not null, enabled bit not null, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6), username varchar(50) not null, email varchar(100) not null, password varchar(100) not null, role enum ('ADMIN','USER') not null, primary key (id)) engine=InnoDB;
create index idx_username on users (username);
create index idx_email on users (email);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
